repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: '^vault/'
  - repo: local
    hooks:
      - id: ansible-vault-header
        name: Ensure Ansible Vault header
        entry: scripts/check-ansible-vault.sh
        language: script
        files: ^vault/.*\.yml$
