---
# Default installation configuration
# Set os_override to force a distribution (e.g. manjaro, fedora, ubuntu)
os_override: ""
machine_preset: ""

# Browser installation flags
install_brave: true
install_firefox: true
install_chromium: false
