---
# Example configuration for linux-dev-playbook
# This file mirrors config.template.yml. Adjust values as needed.

# Force a specific distribution ('arch' or 'fedora') to
# override automatic package manager detection. Use 'arch' for Arch-based
# systems such as Manjaro. Leave empty to use the detected distribution.
os_override: ""

# Optional machine preset overrides for targeted machines.
# Leave empty for generic setup.
machine_preset: "ideapad_330"

# Choose which window manager to install: 'i3' or 'hyprland'.
# Set to 'hyprland' to install the Hyprland compositor and enable the
# optional Wayland features below.
window_manager: hyprland

# Choose which desktop environment to install ('gnome', 'kde', 'xfce', or 'none').
desktop_environment: none

# Choose which file manager to install ('thunar', 'nautilus', or 'none').
file_manager: none

# List of code editors to install (any of 'neovim', 'vim', 'vscode').
code_editors:
  - neovim

# Choose which terminal emulator to install ('alacritty', 'kitty', or 'none').
terminal_emulator: none

# Choose which shell to use ('bash', 'zsh', or 'fish').
shell: zsh

# Choose which AI or productivity tool to install ('clickup' or 'none').
ai_tool: none

# Choose which video player to install ('vlc', 'mpv', or 'none').
video_player: none
# Choose which torrent client to install ('qbittorrent', 'transmission', or 'none').
torrent_client: none

# Choose which terminal file manager to install ('yazi', 'ranger', or 'none').
terminal_file_manager: none

# Choose which application launcher to install ('rofi', 'wofi', or 'none').
app_launcher: none

# Install graphics applications
install_gimp: false
install_inkscape: false

# Install office suite
install_libreoffice: false

# Install audio editor
install_audacity: false

# Install calculator
install_qalculate: false

# Install terminal calendar
install_calcurse: false

# Install database tool
install_dbeaver: false

# Install database modeler
install_pgmodeler: false

# Install graph visualization tools
install_graphviz: false

# Install diagram editor
install_dia: false

# Install Bluetooth and audio support.
install_bluetooth: true

# Install multimedia codecs like ffmpeg and gstreamer.
install_codecs: true

# Dotfiles repository to clone. Leave empty to skip dotfiles setup.
dotfiles_repo: "https://github.com/PcKiLl3r/.dotfiles.git"

# Optional SSH key used to access the dotfiles repository.
# Leave empty when using HTTPS or the default SSH key.
dotfiles_repo_key: ""

# Recurse into submodules when cloning dotfiles.
dotfiles_repo_recursive: false

# Hyprland optional feature flags (effective only when window_manager is 'hyprland')

# Add the current user to the input group (required for some input devices).
add_input_group: true

# Install the SDDM display manager and themes.
install_sddm: false

# Install additional GTK themes for aesthetic customization.
install_gtk_themes: false

# Install the Quickshell Wayland panel.
install_quickshell: false

# Install ROG-specific packages for ASUS ROG devices.
install_rog_packages: false

# Browser installation flags
install_brave: true
install_firefox: true
