---
- name: Setup Linux Development Machine Environment
  hosts: all
  become: true
  vars_files:
    - vault/become_pass.yml
    - vault/bluetooth.yml
    - config.yml

  vars:
    use_on_tv: false
    restore_last_ssh: true

  pre_tasks:
    - name: Include Vars
      ansible.builtin.include_vars:
        file: ./vars/common.yml

    - name: Determine target operating system
      ansible.builtin.set_fact:
        target_os: "{{ os_override | default(ansible_distribution | lower, true) }}"

    - name: Include distro vars
      ansible.builtin.include_vars:
        file: "./vars/{{ target_os }}.yml"

    - name: Show detected operating system
      ansible.builtin.debug:
        msg: "Installing for OS: {{ target_os }}"

    - name: Include Core init tasks
      ansible.builtin.include_tasks:
        file: ./tasks/core.yml

        #    - name: Import GUI Apps Install
        #      ansible.builtin.include_tasks:
        #        file: ./tasks/gui-software.yml
        #      become: false
        #
        #   - name: Import Mobile Dev Install
        #     ansible.builtin.include_tasks:
        #       file: ./tasks/mobile-dev.yml
        #     become: false
        #
        #   TODE make more plays instead of 1 play with many tasks

  tasks:
    - name: Include SSH key restore/create
      ansible.builtin.include_tasks:
        file: ./tasks/ssh.yml
      vars:
        machine_upgrade: "{{ restore_last_ssh }}"

    - name: Import Utility Packages Install
      ansible.builtin.import_tasks:
        file: ./tasks/utils.yml

    - name: Import Dev-Tools Install
      ansible.builtin.import_tasks:
        file: ./tasks/dev-tools.yml

    - name: Import Browser Install
      ansible.builtin.import_tasks:
        file: ./tasks/browsers.yml

    - name: Import Codecs Install
      ansible.builtin.import_tasks:
        file: ./tasks/codecs.yml
      when: install_codecs | bool

    - name: Import ZShell Install
      ansible.builtin.import_tasks:
        file: ./tasks/zsh.yml

    - name: Import Programming Languages/Runtimes Install
      ansible.builtin.import_tasks:
        file: ./tasks/prog-lang.yml

    - name: Import TMux Install
      ansible.builtin.import_tasks:
        file: ./tasks/tmux.yml

    - name: Import NeoVim Install
      ansible.builtin.import_tasks:
        file: ./tasks/neovim.yml

    - name: Import i3 Install
      ansible.builtin.import_tasks:
        file: ./tasks/i3.yml
      when: window_manager == 'i3'

    - name: Import Hyprland Install
      ansible.builtin.import_tasks:
        file: ./tasks/hyprland.yml
      when: window_manager == 'hyprland'

    - name: Import keyboard setup
      ansible.builtin.import_tasks:
        file: ./tasks/keyboard.yml

    - name: Import Bluetooth & audio setup
      ansible.builtin.import_tasks:
        file: ./tasks/bluetooth.yml
      when: install_bluetooth | bool

    - name: Import dotfiles setup
      ansible.builtin.import_tasks:
        file: ./tasks/dotfiles.yml
      when: dotfiles_repo | default('') | length > 0

    - name: Import machine preset overrides
      ansible.builtin.import_tasks:
        file: ./tasks/presets.yml
