---
- name: Setup Linux Development Machine Environment
  hosts: all
  connection: local
  become: true

  vars:
    machine_upgrade_play: true

  tasks:
    - name: Import SSH key restore/create
      ansible.builtin.include_tasks:
        file: ./playbooks/ssh.yml
      vars:
        machine_upgrade: "{{ machine_upgrade_play }}"

    - name: Import Utility Packages Install
      ansible.builtin.import_tasks:
        file: ./playbooks/utils.yml
