---
- name: Setup Linux Development Machine Environment
  hosts: all
  connection: local
  become: true

  tasks:
    - name: Import Utility Packages Install
      import_tasks:
        file: ./playbooks/utils.yml
