---
- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    createhome: true
  become_method: ansible.builtin.sudo

- name: Install setup dependencies
  ansible.builtin.package:
    name: "{{ core_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Clone this repo to mirror real environment
  ansible.builtin.git:
    repo: https://github.com/PcKiLl3r/linux-dev-playbook.git
    dest: ~/personal/linux-dev-playbook
    version: master
  become_user: "{{ username }}"
  become: true

- name: Update apt cache (on Debian based systems only)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

  #- name: Enable Additional Repos for Fedora (Free)
  #  ansible.builtin.pacman:
  #    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
  #    state: present
  #  when: ansible_distribution == 'Fedora'
  #  become: true

- name: Ensure pacman contrib utilities
  ansible.builtin.package:
    name: "{{ core_pacman_contrib_package }}"
    state: present
    use: "{{ pkg_mgr }}"
  when: target_os == 'arch'
