---

- name: Install stow
  ansible.builtin.package:
    name: "{{ dotfiles_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "git@github.com:PcKiLl3r/.dotfiles.git"
    dest: "~/.dotfiles"
    version: master
    key_file: "/home/{{ username }}/.ssh/id_rsa"
  become: true
  become_user: "{{ username }}"

- name: Stow .dotfiles
  ansible.builtin.command:
    cmd: ./run
    # creates:
  args:
    chdir: "/home/{{ username }}/.dotfiles"
  changed_when: false
  become: false
