---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ gui_dependencies_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

#- name: Add GUI Apps Repos
#  ansible.builtin.yum_repository:
#    name: brave-browser
#    description: Brave browser repo
#    baseurl: 'https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo'
#
#- name: Enable Brave repo
#  community.general.dnf_config_manager:
#    name: brave-browser
#    state: enabled
#
#- name: Add rpm_key
#  ansible.builtin.rpm_key:
#    state: present
#
#- name: Add brave rpm key
#  ansible.builtin.rpm_key:
#    key: 'https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
#    state: present
#
#- name: update
#  ansible.builtin.pacman:
#    name: "*"
#    state: latest
#
- name: Install GUI software
  ansible.builtin.package:
    name: "{{ gui_software_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Ensure dependency for brave installer is present
  ansible.builtin.package:
    name: "{{ brave_dependency_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

#- name: Install Brave
#  ansible.builtin.yum:
#    name: brave-browser
#    state: present
- name: Import install Brave browser role
  import_role:
    name: staticdev.brave
  when: install_brave | bool and target_os in ['debian', 'ubuntu']

- name: Install Blender
  ansible.builtin.package:
    name: "{{ blender_package }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install Postman dependencies
  ansible.builtin.package:
    name: "{{ postman_dependency_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Download Postman
  ansible.builtin.get_url:
    url: https://dl.pstmn.io/download/latest/linux_64
    dest: /tmp/postman.tar.gz

- name: Install Postman
  ansible.builtin.unarchive:
    src: /tmp/postman.tar.gz
    dest: /opt/postman

- name: Add Postman to path... TODO
  debug: TODO
