---
- name: Install KDE Plasma desktop environment
  ansible.builtin.package:
    name: "{{ kde_packages }}"
    state: present
    use: "{{ pkg_mgr }}"
  register: kde_install

- name: Track desktop environment installation state
  ansible.builtin.set_fact:
    desktop_install_changed: >-
      {{ (
            desktop_install_changed | default(false)
            or (kde_install.changed | default(false))
          ) | bool }}

- name: Record KDE reboot reason when packages were installed
  ansible.builtin.set_fact:
    desktop_install_change_reason: >-
      {{ desktop_install_change_reason | default([]) + [
           'KDE Plasma packages were installed or updated during this run.'
         ] }}
  when: kde_install.changed | default(false)

- name: Report KDE installation summary
  ansible.builtin.debug:
    msg:
      - "KDE package task reported changes: {{ kde_install.changed | default(false) }}"
      - "desktop_install_changed: {{ desktop_install_changed | default(false) }}"
  when: kde_install is defined
