---

- name: Create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'
  become: false

- name: Try to copy existing key from vault if present
  ansible.builtin.copy:
    src: ../vault/id_rsa
    dest: ~/.ssh/id_rsa
    mode: '0600'
  when: machine_upgrade | bool
  become: false

- name: If no key was restored, create a now one.
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
  when: not machine_upgrade
  become: false

- name: Ensure GitHub is a known host
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
  become: false

- name: Add SSH key to agent
  ansible.builtin.command:
    cmd: ssh-add ~/.ssh/id_rsa
  environment:
    SSH_AUTH_SOCK: "{{ ansible_env.SSH_AUTH_SOCK }}"
  changed_when: false
  when: ansible_env.SSH_AUTH_SOCK is defined
  become: false
