---
- name: Install XFCE desktop environment
  ansible.builtin.package:
    name: "{{ xfce_packages }}"
    state: present
    use: "{{ pkg_mgr }}"
  register: xfce_install

- name: Track desktop environment installation state
  ansible.builtin.set_fact:
    desktop_install_changed: >-
      {{ (
            desktop_install_changed | default(false)
            or (xfce_install.changed | default(false))
          ) | bool }}
