---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Docker container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command | default(omit) }}"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        cgroupns_mode: "{{ item.cgroupns_mode | default(omit) }}"
        pre_build_image: true
        state: started
      loop: "{{ molecule_yml.platforms }}"
      register: server
      async: 300
      poll: 0

    - name: Wait for containers to start
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _wait
      until: _wait.finished
      retries: 30
      delay: 1
      loop: "{{ server.results }}"

    - name: Populate instance config dict
      ansible.builtin.set_fact:
        instance_conf_dict:
          instance: "{{ item.item.name }}"
          address: "{{ item.invocation.module_args.name }}"
          user: root
          port: 22
          identity_file: ""
      loop: "{{ _wait.results }}"
      register: instance_config_dict

    - name: Convert instance config dict to a list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
