---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "{{ lookup('env', 'MOLECULE_DISTRO') | default('fedora') }}"
    image: "{{ lookup('env', 'MOLECULE_IMAGE') | default('geerlingguy/docker-fedora41-ansible:latest') }}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
