---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: ../../collections/requirements.yml
    collections-path: ../../collections
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "${MOLECULE_DISTRO:-fedora}"
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-fedora41-ansible:latest}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    cleanup: cleanup.yml
verifier:
  name: ansible
