---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # - name: arch
  #   image: "geerlingguy/docker-archlinux-ansible:latest"
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  - name: fedora
    image: "geerlingguy/docker-fedora41-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
