---
- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    createhome: true
  become_method: "sudo"

- name: Install setup dependencies
  ansible.builtin.dnf:
    name:
      - git
    state: present

- name: Clone this repo to mirror real environment
  ansible.builtin.git:
    repo: https://github.com/PcKiLl3r/linux-dev-playbook.git
    dest: ~/personal/linux-dev-playbook
  become_user: "{{ username }}"

- name: Update apt cache (on Debian based systems only)
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

  #- name: Enable Additional Repos for Fedora (Free)
  #  ansible.builtin.dnf:
  #    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
  #    state: present
  #  when: ansible_distribution == 'Fedora'
  #  become: true

- name: Enchance dnf
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

