---
- name: Install Development Tools
  ansible.builtin.pacman:
    name:
      - git
      - docker
      - docker-compose
      - python-pip

- name: Ensure Group "docker" Exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
  become: false

- name: Add User to "docker" Group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker

- name: Add username to git Config
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ username }}"
  become: false

- name: Add email to git Config
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
  become: false
