---

- name: Install stow
  ansible.builtin.pacman:
    name: stow
    state: present

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: https://github.com/PcKiLl3r/.dotfiles.git
    dest: ~/.dotfiles
  become_user: "{{ username }}"

- name: Stow .dotfiles
  ansible.builtin.command:
    cmd: ./run
    # creates:
  args:
    chdir: "/home/{{ username }}/.dotfiles"
  become: false
