---

- name: Clone dotfiles repo 
  ansible.builtin.git:
    repo: https://github.com/PcKiLl3r/.dotfiles
    dest: ~/.dotfiles
  become: true
  become_user: "{{ username }}"

- name: Stow .dotfiles
  ansible.builtin.command:
    cmd: ./run
    # creates:
  args:
    chdir: "/home/{{ username }}/.dotfiles"
