---
- name: Install dependencies
  ansible.builtin.pacman:
    name:
      - base-devel
    state: present

#- name: Add GUI Apps Repos
#  ansible.builtin.yum_repository:
#    name: brave-browser
#    description: Brave browser repo
#    baseurl: 'https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo'
#
#- name: Enable Brave repo
#  community.general.dnf_config_manager:
#    name: brave-browser
#    state: enabled
#
#- name: Add rpm_key
#  ansible.builtin.rpm_key:
#    state: present
#
#- name: Add brave rpm key
#  ansible.builtin.rpm_key:
#    key: 'https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
#    state: present
#
#- name: update
#  ansible.builtin.pacman:
#    name: "*"
#    state: latest
#
- name: Install GUI software
  ansible.builtin.pacman:
    name:
      - discord
    state: present

- name: Ensure dependency for brave installer is present
  ansible.builtin.pacman:
    name: acl
    state: present

#- name: Install Brave
#  ansible.builtin.yum:
#    name: brave-browser
#    state: present
- name: Import install Brave browser role
  import_role:
    name: staticdev.brave

- name: Install Blender
  ansible.builtin.pacman:
    name: blender
    state: present

- name: Install Postman dependencies
  ansible.builtin.pacman:
    name: openssl
    state: present

- name: Download Postman
  ansible.builtin.get_url:
    url: https://dl.pstmn.io/download/latest/linux_64
    dest: /tmp/postman.tar.gz

- name: Install Postman
  ansible.builtin.unarchive:
    src: /tmp/postman.tar.gz
    dest: /opt/postman

- name: Add Postman to path... TODO
  debug: TODO
