---
- name: Install mobile-dev utils
  ansible.builtin.package:
    name: "{{ mobile_dev_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install global npm packages for Native
  community.general.npm:
    name: eas-cli
    global: true
