---
#- name: Check if newer version of NeoVim is available
# todo - check if newer version with git clone first

#- name: Remove old versions of neovim
#  ansible.builtin.file:
#    path: "{{ home }}/neovim"
#    state: absent

- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ home }}/neovim"
    depth: 1
    version: stable
  register: gitclone_result
  become: false

- name: Install NeoVim Dependencies
  ansible.builtin.pacman:
    name:
      - cmake
      - gettext
      #- lua5.1
      - lua
      - ninja-build
      - gcc
      - make
      - unzip
      - curl
      - glibc
      - wget
      - libevent
      - readline
      - ncurses

- name: Plenary
  ansible.builtin.git:
    repo: "https://github.com/nvim-lua/plenary.nvim.git"
    dest: "{{ personal }}/plenary.nvim"
    depth: 1
  become: false

# TODO should install neovim with:
    # make CMAKE_BUILD_TYPE=RelWithDebInfo
    # git checkout stable
    # then make install
    #
    # also change install location...

# TODO fix zsh not stowing propperly
    #  remove .zshrc then stow
    #  source .zshrc and zsh_profile after

- name: Install NeoVim with Make
  ansible.builtin.command: sudo make install
  args:
    chdir: "{{ home }}/neovim"
  when: gitclone_result.changed
  become: false

- name: Install Rust
  ansible.builtin.pacman:
    name:
      - rust
      - cargo

- name: Install Stylua
  ansible.builtin.shell:
    cmd: cargo install stylua
  become: false

#- name: Install LuaRocks
#  ansible.builtin.shell:
#    chdir: "{{ dev }}"
#    cmd: ./resources/luarocks.sh
#  become: false
- name: Install LuaRocks
  ansible.builtin.pacman:
    name: luarocks
    state: present

- name: Install LuaCheck
  ansible.builtin.shell:
    cmd: luarocks install luacheck
