---
- name: Install nodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present
  become: true

- name: Install yarn package manager
  ansible.builtin.dnf:
    name: yarnpkg
    state: present
  become: true

- name: Install C, C++ Development Tools
  ansible.builtin.dnf:
    name:
      - gcc
      - g++
      - gdb
      - glibc-devel
      - valgrind
      - gcc-c++
      - clang
      - cpp
      - clang
  become: true

- name: Install Python Dev Tools
  ansible.builtin.dnf:
      name:
        - python3-pip
  become: true

- name: Install GO
  ansible.builtin.dnf:
    name:
      - go
  become: true

- name: Install Lua
  ansible.builtin.dnf:
    name:
      - lua5.1
      - lua5.1-devel
      - luarocks
  become: true
