---
- name: Install nodeJS
  ansible.builtin.pacman:
    name: nodejs
    state: present

- name: Install yarn package manager
  ansible.builtin.pacman:
    name: yarn
    state: present

- name: Install C, C++ Development Tools
  ansible.builtin.pacman:
    name:
      - base-devel
      - gdb
      - valgrind
      - clang

- name: Install Python Dev Tools
  ansible.builtin.pacman:
    name:
      - python-pip

- name: Install GO
  ansible.builtin.pacman:
    name:
      - go

- name: Install Lua
  ansible.builtin.pacman:
    name:
      - lua
      - luarocks
