---
- name: Install nodeJS
  ansible.builtin.package:
    name: "{{ prog_lang_nodejs_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install yarn package manager
  ansible.builtin.package:
    name: "{{ prog_lang_yarn_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install C, C++ Development Tools
  ansible.builtin.package:
    name: "{{ prog_lang_cdev_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install Python Dev Tools
  ansible.builtin.package:
    name: "{{ prog_lang_python_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install GO
  ansible.builtin.package:
    name: "{{ prog_lang_go_packages }}"
    state: present
    use: "{{ pkg_mgr }}"

- name: Install Lua
  ansible.builtin.package:
    name: "{{ prog_lang_lua_packages }}"
    state: present
    use: "{{ pkg_mgr }}"
