---
- name: Create .ssh directory
  file:
    path: "~/.ssh"
    state: directory
    mode: '0755'

- name: Try to copy existing key from vault if present



- name: If no key was restored, create a now one.
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
  when:
