---
- name: Install Useful Utilities
  ansible.builtin.pacman:
    name:
      - fzf
      - ripgrep
      - pavucontrol
      - xclip
      - jq
      - tldr
      - shutter
      - trash-cli
    state: present
