---
- name: Ensure Zsh with dependencies are installed
  ansible.builtin.pacman:
    name: zsh
    state: present

- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  become: false

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  changed_when: "'The $ZSH folder already exists' not in ohmyzsh_result.stdout"
  become: false

- name: Set default shell to zsh
  command: chsh -s /usr/bin/zsh
  register: chsh_result
  changed_when: "'Shell not changed.' not in chsh_result.stderr"
