# ---
# name: CI
# 'on':
#   pull_request:
#   push:
#     branches:
#       - master
#
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install ansible ansible-lint yamllint molecule pre-commit detect-secrets
#           ansible-galaxy install -r requirements.yml
#       - name: Run pre-commit
#         run: pre-commit run --all-files
#       - name: Run make lint
#         run: make lint
#       - name: Run make test
#         run: make test
#         if: false
